In [1]:
import numpy as np

In [2]:
# Create an array by passing in a list of lists.
ratings = np.array([[94, 89, 63, 45], [93, 92, 48, 23], [92, 94, 56, 98]])

ratings

array([[94, 89, 63, 45],
       [93, 92, 48, 23],
       [92, 94, 56, 98]])

In [3]:
ratings.shape

(3, 4)

In [4]:
# Create an array of ones – pass in shape as a tuple.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# Create an array of zeros – pass in shape as a tuple.
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Create an array of random values – pass in shape as a tuple.
np.random.random((3, 3))

array([[0.56207165, 0.43248177, 0.73837242],
       [0.43380262, 0.34892328, 0.50023183],
       [0.49920007, 0.18475237, 0.42755891]])

In [7]:
# Whole array.
ratings

array([[94, 89, 63, 45],
       [93, 92, 48, 23],
       [92, 94, 56, 98]])

In [8]:
# Select the top left element.
ratings[0, 0]

94

In [9]:
# Select the first row.
ratings[0, :]

array([94, 89, 63, 45])

In [10]:
# Select the first column.
ratings[:, 0]

array([94, 93, 92])

In [11]:
# Select the first two rows and first two columns.
ratings[0:2, 0:2]

array([[94, 89],
       [93, 92]])

In [15]:
ratings[ratings > 90]

array([94, 93, 92, 92, 94, 98])

In [16]:
# Append an extra row – note that axis=0.
ratings_extra_row = np.append(ratings, [[92, 88, 78, 55]], axis=0)

ratings_extra_row

array([[94, 89, 63, 45],
       [93, 92, 48, 23],
       [92, 94, 56, 98],
       [92, 88, 78, 55]])

In [17]:
# Delete the 3rd row – note that axis=0.
ratings_del_row = np.delete(ratings, [2], axis=0)

ratings_del_row

array([[94, 89, 63, 45],
       [93, 92, 48, 23]])

In [18]:
# Sum of all elements in the array.
ratings.sum()

887

In [19]:
# Sum of each row.
ratings.sum(axis=1)

array([291, 256, 340])

In [20]:
# Sum of each column.
ratings.sum(axis=0)

array([279, 275, 167, 166])

In [21]:
# Min of each row.
ratings.min(axis=1)

array([45, 23, 56])

In [22]:
# Finds the index of the maximum value in the entire array
overall_max_index = np.argmax(ratings)

In [23]:
# Finds the index of the minimum value along each column
min_indices_per_column = np.argmin(ratings, axis=0)